FROM registry.access.redhat.com/ubi8/ubi-minimal
ARG VERSION
LABEL name="Villanova K8S Database Service Controller" \
      vendor="Villanova" \
      version="v${VERSION}" \
      release="7.0" \
      summary="This container processes the VillanovaDatabaseService custom resource and makes the database service available." \
      description="This is a run-to-completion container. It processes new VillanovaDatabaseService Custom \
                   Resources. If the VillanovaDatbaseService specifies that a deployment should be created, \
                   it deploys an instance of the specified database Docker image  to your cluster. Alternatively, \
                   it just creates Kubernetes service that points to an external database service. \
                   Subsequent executions of this container against the same VillanovaDatbaseService will patch the existing \
                   deployment resources"
COPY target/generated-resources/licenses /licenses
COPY target/*-runner /work/application
RUN chmod 775 /work/application
CMD ["./application","-Djava.library.path=/work/lib"]
