FROM villanova/villanova-k8s-operator-common:7.3.0
ARG VERSION
LABEL name="Villanova K8S Database Service Controller" \
      vendor="Villanova" \
      version="v${VERSION}" \
      release="7.1" \
      summary="This container processes the VillanovaDatabaseService custom resource and makes the database service available." \
      description="This is a run-to-completion container. It processes new VillanovaDatabaseService Custom \
                   Resources. If the VillanovaDatbaseService specifies that a deployment should be created, \
                   it deploys an instance of the specified database Docker image  to your cluster. Alternatively, \
                   it just creates Kubernetes service that points to an external database service. \
                   Subsequent executions of this container against the same VillanovaDatbaseService will patch the existing \
                   deployment resources"
ENV JAVA_OPTIONS="-Djava.util.logging.manager=org.jboss.logmanager.LogManager"
COPY target/quarkus-app/lib/main/*.jar /deployments/lib/main/
COPY target/quarkus-app/*.jar /deployments/
COPY target/quarkus-app/app/ /deployments/app/
COPY target/quarkus-app/quarkus/ /deployments/quarkus/
ENTRYPOINT [ "/deployments/run-java.sh" ]
